// @generated by protoc-gen-es v1.7.2
// @generated from file couscous.proto (package couscous, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";

/**
 * @generated from message couscous.NewChannelRequest
 */
export declare class NewChannelRequest extends Message<NewChannelRequest> {
  constructor(data?: PartialMessage<NewChannelRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "couscous.NewChannelRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): NewChannelRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): NewChannelRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): NewChannelRequest;

  static equals(a: NewChannelRequest | PlainMessage<NewChannelRequest> | undefined, b: NewChannelRequest | PlainMessage<NewChannelRequest> | undefined): boolean;
}

/**
 * @generated from message couscous.Chat
 */
export declare class Chat extends Message<Chat> {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  constructor(data?: PartialMessage<Chat>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "couscous.Chat";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Chat;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Chat;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Chat;

  static equals(a: Chat | PlainMessage<Chat> | undefined, b: Chat | PlainMessage<Chat> | undefined): boolean;
}

/**
 * @generated from message couscous.MessageRequest
 */
export declare class MessageRequest extends Message<MessageRequest> {
  /**
   * @generated from field: string message = 1;
   */
  message: string;

  /**
   * @generated from field: string chat_id = 2;
   */
  chatId: string;

  constructor(data?: PartialMessage<MessageRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "couscous.MessageRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): MessageRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): MessageRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): MessageRequest;

  static equals(a: MessageRequest | PlainMessage<MessageRequest> | undefined, b: MessageRequest | PlainMessage<MessageRequest> | undefined): boolean;
}

/**
 * @generated from message couscous.MessageResponse
 */
export declare class MessageResponse extends Message<MessageResponse> {
  /**
   * @generated from field: string message = 1;
   */
  message: string;

  constructor(data?: PartialMessage<MessageResponse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "couscous.MessageResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): MessageResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): MessageResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): MessageResponse;

  static equals(a: MessageResponse | PlainMessage<MessageResponse> | undefined, b: MessageResponse | PlainMessage<MessageResponse> | undefined): boolean;
}

