// @generated by protoc-gen-connect-es v1.4.0 with parameter "target=ts"
// @generated from file couscous.proto (package couscous, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { Chat, MessageRequest, MessageResponse, NewChannelRequest } from "./couscous_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service couscous.Couscous
 */
export const Couscous = {
  typeName: "couscous.Couscous",
  methods: {
    /**
     * @generated from rpc couscous.Couscous.NewChannel
     */
    newChannel: {
      name: "NewChannel",
      I: NewChannelRequest,
      O: Chat,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc couscous.Couscous.Discuss
     */
    discuss: {
      name: "Discuss",
      I: MessageRequest,
      O: MessageResponse,
      kind: MethodKind.ServerStreaming,
    },
  }
} as const;

