// @generated by protoc-gen-es v1.7.2
// @generated from file couscous.proto (package couscous, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { proto3 } from "@bufbuild/protobuf";

/**
 * @generated from message couscous.NewChannelRequest
 */
export const NewChannelRequest = proto3.makeMessageType(
  "couscous.NewChannelRequest",
  [],
);

/**
 * @generated from message couscous.Chat
 */
export const Chat = proto3.makeMessageType(
  "couscous.Chat",
  () => [
    { no: 1, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * @generated from message couscous.MessageRequest
 */
export const MessageRequest = proto3.makeMessageType(
  "couscous.MessageRequest",
  () => [
    { no: 1, name: "message", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "chat_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * @generated from message couscous.MessageResponse
 */
export const MessageResponse = proto3.makeMessageType(
  "couscous.MessageResponse",
  () => [
    { no: 1, name: "message", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

